# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\hw1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("2020 Cvdl Hw1")
        MainWindow.resize(682, 422)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 50, 341, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(160, 30, 171, 141))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn1_1 = QtWidgets.QPushButton(self.frame)
        self.btn1_1.setGeometry(QtCore.QRect(10, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn1_1.setFont(font)
        self.btn1_1.setObjectName("btn1_1")
        self.btn1_2 = QtWidgets.QPushButton(self.frame)
        self.btn1_2.setGeometry(QtCore.QRect(10, 70, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn1_2.setFont(font)
        self.btn1_2.setObjectName("btn1_2")
        self.btn1_3 = QtWidgets.QPushButton(self.frame_2)
        self.btn1_3.setGeometry(QtCore.QRect(30, 90, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn1_3.setFont(font)
        self.btn1_3.setObjectName("btn1_3")
        self.btn1_4 = QtWidgets.QPushButton(self.frame)
        self.btn1_4.setGeometry(QtCore.QRect(10, 130, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn1_4.setFont(font)
        self.btn1_4.setObjectName("btn1_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 20, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(410, 50, 200, 45))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.btn2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2_1.setGeometry(QtCore.QRect(430, 53, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn2_1.setFont(font)
        self.btn2_1.setObjectName("btn2_1")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(410, 120, 200, 45))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 90, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3_1.setGeometry(QtCore.QRect(430, 123, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn3_1.setFont(font)
        self.btn3_1.setObjectName("btn3_1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(400, 160, 200, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4_1.setGeometry(QtCore.QRect(430, 185, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn4_1.setFont(font)
        self.btn4_1.setObjectName("btn4_1")
        self.btn4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4_2.setGeometry(QtCore.QRect(430, 225, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btn4_2.setFont(font)
        self.btn4_2.setObjectName("btn4_2")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cboxImgNum = QtWidgets.QComboBox(self.frame_2)
        self.cboxImgNum.setGeometry(QtCore.QRect(10, 50, 151, 31))
        self.cboxImgNum.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cboxImgNum.setObjectName("cboxImgNum")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.cboxImgNum.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 50, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(410, 185, 200, 90))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("2020 Cvdl HW1", "2020 Cvdl HW1"))
        self.label.setText(_translate("MainWindow", "1. Calibration"))
        self.btn1_1.setText(_translate("MainWindow", "1.1 Find Corners"))
        self.btn1_2.setText(_translate("MainWindow", "1.2 Find Intrinsic"))
        self.btn1_3.setText(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.label_5.setText(_translate("MainWindow", "1.3 Find Extrinsic"))
        self.label_6.setText(_translate("MainWindow", "Select image"))
        self.cboxImgNum.setItemText(0, _translate("MainWindow", "1"))
        self.cboxImgNum.setItemText(1, _translate("MainWindow", "2"))
        self.cboxImgNum.setItemText(2, _translate("MainWindow", "3"))
        self.cboxImgNum.setItemText(3, _translate("MainWindow", "4"))
        self.cboxImgNum.setItemText(4, _translate("MainWindow", "5"))
        self.cboxImgNum.setItemText(5, _translate("MainWindow", "6"))
        self.cboxImgNum.setItemText(6, _translate("MainWindow", "7"))
        self.cboxImgNum.setItemText(7, _translate("MainWindow", "8"))
        self.cboxImgNum.setItemText(8, _translate("MainWindow", "9"))
        self.cboxImgNum.setItemText(9, _translate("MainWindow", "10"))
        self.cboxImgNum.setItemText(10, _translate("MainWindow", "11"))
        self.cboxImgNum.setItemText(11, _translate("MainWindow", "12"))
        self.cboxImgNum.setItemText(12, _translate("MainWindow", "13"))
        self.cboxImgNum.setItemText(13, _translate("MainWindow", "14"))
        self.cboxImgNum.setItemText(14, _translate("MainWindow", "15"))
        self.btn1_4.setText(_translate("MainWindow", "1.4 Find Distortion"))
        self.label_2.setText(_translate("MainWindow", "2. Augmented Reality"))
        self.btn2_1.setText(_translate("MainWindow", "2.1 Augmented Reality"))
        self.label_3.setText(_translate("MainWindow", "3. Stereo Disparity Map"))
        self.btn3_1.setText(_translate("MainWindow", "3.1 Stereo Disparity Map"))
        self.label_4.setText(_translate("MainWindow", "4. SIFT"))
        self.btn4_1.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.btn4_2.setText(_translate("MainWindow", "4.2 Matched keypoints"))